### ISSUE TITLE
CAMB commit bfb733c breaks orphics.cosmology

### ISSUE THREAD

**Issue by dylancromer** [msyriac/orphics#19]
In [this](https://github.com/cmbant/CAMB/commit/bfb733c321a85148187e1814f7997d311f9d2156#diff-3ec73f13e116c117a5aea17eabf85d84) commit of CAMB, they have removed global variables to begin support for multiple CAMBData instances. This causes orphics.cosmology to break when run against the latest commit to the devel branch of CAMB. 

I get the error
```
  File "/Users/dylan/Development/szar/szar/counts.py", line 217, in __init__
    Cosmology.__init__(self,paramDict,constDict,lmax,clTTFixFile,skipCls,pickling,fill_zero,dimensionless=dimensionless,verbose=verbose,skipPower=skipPower,skip_growth=skip_growth,low_acc=low_acc,nonlinear=False)
  File "/Users/dylan/Development/orphics/orphics/cosmology.py", line 150, in __init__
    self.chistar = self.results.conformal_time(0)- model.tau_maxvis.value
AttributeError: module 'camb.model' has no attribute 'tau_maxvis'
```
when trying to create a ClusterCosmology object in `szar.counts`.

**Comment by msyriac** [comment]
@dylancromer Could you check if this is fixed now?

**Comment by dylancromer** [comment]
@msyriac Looks like you're good!
